import 'package:flutter/material.dart';
import '../api/scan_summary.dart';
import 'theme/nsfw_theme.dart';

/// Bottom-sheet body summarising a completed scan. Show via
/// `showModalBottomSheet`. Counter values animate from 0 to their final value
/// using a [TweenAnimationBuilder] so the sheet feels alive when it appears.
class NsfwScanSummarySheet extends StatelessWidget {
  final ScanSummary summary;
  final NsfwTheme? theme;
  final VoidCallback? onClose;
  final List<Widget>? extraActions;
  final String closeLabel;

  /// Optional share callback. When non-null the sheet renders a "Share Report"
  /// button next to [closeLabel]; the callback receives a pre-formatted text
  /// summary so the host can pipe it through `share_plus` (or any other
  /// channel) without the plugin pulling in extra dependencies.
  final void Function(String text)? onShare;

  const NsfwScanSummarySheet({
    super.key,
    required this.summary,
    this.theme,
    this.onClose,
    this.extraActions,
    this.closeLabel = 'Close',
    this.onShare,
  });

  /// Default formatted report text used when the host invokes [onShare]
  /// without producing its own copy. Public so consumers can compose / extend.
  static String defaultReportText(ScanSummary s) {
    final pct = s.totalScanned == 0
        ? 0
        : ((s.nsfwCount / s.totalScanned) * 100).round();
    String dur(Duration d) {
      if (d.inMinutes > 0) {
        return '${d.inMinutes}m ${d.inSeconds.remainder(60)}s';
      }
      return '${d.inSeconds}s';
    }

    return 'NSFW Scan Report\n'
        '${s.totalScanned} scanned, ${s.nsfwCount} NSFW ($pct%), ${dur(s.elapsed)}\n'
        'Generated by nsfw_detect';
  }

  @override
  Widget build(BuildContext context) {
    final t = theme ?? NsfwTheme.defaults();
    final s = t.spacing;
    final radius = BorderRadius.vertical(top: Radius.circular(s.xl));

    return Container(
      decoration: BoxDecoration(
        color: t.surface,
        borderRadius: radius,
        boxShadow: t.elevation.high,
      ),
      child: SafeArea(
        top: false,
        child: Padding(
          padding: EdgeInsets.fromLTRB(s.xl, s.md, s.xl, s.xl),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Center(
                child: Container(
                  width: 36,
                  height: 4,
                  decoration: BoxDecoration(
                    color: t.outline,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              SizedBox(height: s.lg),
              Row(children: [
                Icon(
                  summary.wasCancelled
                      ? Icons.info_outline_rounded
                      : Icons.check_circle_rounded,
                  color: summary.wasCancelled ? t.onSurfaceMuted : t.success,
                  size: 22,
                ),
                SizedBox(width: s.sm),
                Text(
                  summary.wasCancelled ? 'Scan Cancelled' : 'Scan Complete',
                  style: t.typography.title,
                ),
              ]),
              SizedBox(height: s.xs),
              Text(_formatDuration(summary.elapsed), style: t.typography.caption),
              SizedBox(height: s.lg),
              _row(t, 'Total scanned', summary.totalScanned, t.onSurface),
              _row(t, 'NSFW found', summary.nsfwCount, t.gallery.nsfwColor),
              _row(t, 'Safe', summary.safeCount, t.gallery.safeColor),
              _row(t, 'Skipped', summary.skippedCount, t.onSurfaceMuted),
              _row(t, 'Errors', summary.failedCount,
                  t.gallery.suggestiveColor),
              SizedBox(height: s.lg),
              if (extraActions != null && extraActions!.isNotEmpty) ...[
                ...extraActions!,
                SizedBox(height: s.sm),
              ],
              Row(
                children: [
                  if (onShare != null) ...[
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () =>
                            onShare!.call(defaultReportText(summary)),
                        icon: Icon(Icons.share_rounded, color: t.accent),
                        label: Text(
                          'Share',
                          style: TextStyle(
                              color: t.accent, fontWeight: FontWeight.w700),
                        ),
                        style: OutlinedButton.styleFrom(
                          side: BorderSide(color: t.accent),
                          padding: EdgeInsets.symmetric(vertical: s.md - 2),
                        ),
                      ),
                    ),
                    SizedBox(width: s.sm),
                  ],
                  Expanded(
                    flex: onShare != null ? 1 : 1,
                    child: FilledButton(
                      onPressed:
                          onClose ?? () => Navigator.of(context).maybePop(),
                      style:
                          FilledButton.styleFrom(backgroundColor: t.accent),
                      child: Text(closeLabel),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _row(NsfwTheme t, String label, int value, Color color) => Padding(
        padding: EdgeInsets.symmetric(vertical: t.spacing.xs),
        child: Row(
          children: [
            Expanded(child: Text(label, style: t.typography.body.copyWith(color: t.onSurfaceMuted))),
            TweenAnimationBuilder<double>(
              tween: Tween(begin: 0, end: value.toDouble()),
              duration: t.animations.normal,
              curve: t.animations.curve,
              builder: (_, v, __) => Text(
                v.round().toString(),
                style: t.typography.body.copyWith(
                  color: color,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
          ],
        ),
      );

  String _formatDuration(Duration d) {
    if (d.inMinutes > 0) {
      return '${d.inMinutes}m ${d.inSeconds.remainder(60)}s';
    }
    return '${d.inSeconds}s';
  }
}
